### DISCUSSION TITLE
Using powetools as a layer and 'sam local invoke' command

### DISCUSSION THREAD

**Discussion by MrTomerLevi** [aws-powertools/powertools-lambda-python#348] [Q&A] [answered]
Hello,
I'm using SAM and integrated powetools as a lambda layer into my lambda functions.

When running`sam local invoke` to test my functions locally, I get a missing module exception at:
`from aws_lambda_powertools import Logger, Tracer`

This error makes sense since `aws_lambda_powertools` module is not added to lambda functions locally.
Is there any possible way I can use powertolls layer locally?

** As a workaround, I added `aws-lambda-powertools==1.11.0` to my `requirements.txt`, this enables me to test locally but makes the build process heavier (and my lambda zip file larger)

Thank you all,
Tomer

**Comment by heitorlessa** [comment]
Hey Tomer -  [SAM CLI downloads Layers and make them available in the local Docker container](https://aws.amazon.com/blogs/compute/working-with-aws-lambda-and-lambda-layers-in-aws-sam/), but it sounds like it's not being the case here.

Could you share what version of SAM CLI you're using so we can try reproducing that too?

Pinging @am29d to see if he has the bandwidth to test today, otherwise I'll create a dummy project on Monday to test this out :)

Thanks for reaching out!

**Reply by am29d** [reply]
I will take a look.

**Reply by MrTomerLevi** [reply]
Hi @heitorlessa 
Thanks for helping. 

I'm using sam cli version 1.21.1

**Comment by am29d** [comment]
Hi Tomer,

thanks for reaching out! I have checked the behaviour on an example project and the correct workflow is to run `sam build` before `sam local invoke`. This has nothing to do with the layers or anything. By running the build command sam will create `.aws-sam/build/HelloWorldFunction` directory with all the dependencies. If you run `sam local invoke` this build directory will be mounted into the local runtime:

```
Invoking app.lambda_handler (python3.8)
Skip pulling image and use local one: amazon/aws-sam-cli-emulation-image-python3.8:rapid-1.18.2.

Mounting [REDACTED]/sam-example/.aws-sam/build/HelloWorldFunction as /var/task:ro,delegated inside runtime container
START RequestId: 31f4a484-b494-4a23-aa1c-69b862523cb2 Version: $LATEST
[...]
{"statusCode": 200, "body": "{\"hello\": \"world\"}"}
```

if you run the local invoke command without this folder, the dependencies are missing. So make sure to always build run `sam build` when you add new dependencies to your `requirements.txt` or layers in `template.yml`.

**Reply by MrTomerLevi** [reply]
Hi Alex, 
Thanks for helping.

My SAM template looks like the following:

```
  AwsLambdaPowertoolsPythonLayer:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:eu-west-1:057560766410:applications/aws-lambda-powertools-python-layer
        SemanticVersion: 1.11.0
  
  AuthorizerLambda:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: task_functions/
      Handler: task_auth.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
          LOG_LEVEL: INFO
          POWERTOOLS_SERVICE_NAME: AuthorizerLambda
      Layers:
        - !GetAtt AwsLambdaPowertoolsPythonLayer.Outputs.LayerVersionArn
```

When running:
`sam build --use-container`

This log message is shown:
```
2021-03-22 15:16:53 Requested to create CFN template arn:aws:serverlessrepo:eu-west-1:057560766410:applications/aws-lambda-powertools-python-layer/1.11.0 in serverless application repo.
```

Same log message appears after I run:
`sam local invoke  -e events/appsync.json TaskCreateLambda`

I couldn't fund aws_lambda_powertools inside my build folder: `.aws-sam/build/TaskCreateLambda`
