### DISCUSSION TITLE
openAPI spec generation - APIGatewayRestResolver - Pydantic Field - serialization_alias

### DISCUSSION THREAD

**Discussion by MCR2019** [aws-powertools/powertools-lambda-python#4507] [General]
There a good chance that I'm not doing things in the correct way here but interested in other peoples thoughts on the following.

I'm using an `APIGatewayRestResolver` with `enable_validation=True` and specifying the return type as a `Pydantic` model. 
The `Pydantic` model has a `Field` where I set `alias` as well as `serialization_alias`. So the field in the response has the key specified by`seriliazation_alias` as I'd expect.
Where I generate an openAPI spec though, the response in the schema has the `alias` value.

Hopefully this example code make this clearer:
```
import json

from pydantic import BaseModel, ConfigDict, Field

from aws_lambda_powertools.event_handler import APIGatewayRestResolver
from aws_lambda_powertools.utilities.data_classes import APIGatewayProxyEvent, event_source
from aws_lambda_powertools.utilities.typing import LambdaContext

app = APIGatewayRestResolver(enable_validation=True)


class User(BaseModel):

    model_config = ConfigDict(extra="forbid")

    post_town: str = Field(alias="postTown", serialization_alias="post_town")


@app.get(
    "/",
    responses={
        200: {
            "description": "Hello 200",
            "content": {"application/json": {"model": User}},
        },
    },
)
def get() -> User:
    return {"postTown": "test value"}


@event_source(data_class=APIGatewayProxyEvent)
def lambda_handler(event: APIGatewayProxyEvent, context: LambdaContext):
    return app.resolve(event.raw_event, context)


class TestEndpoints:

    def test_get(self):
        get_event = {"httpMethod": "GET", "path": "/"}
        lambda_response = lambda_handler(get_event, LambdaContext)

        assert json.loads(lambda_response["body"]) == {"post_town": "test value"}
        assert lambda_response["statusCode"] == 200

        print(app.get_openapi_json_schema())
``` 

In the above code the response body is: `{"post_town": "test value"}` however in the generated openAPI spec the response schema is:

```
"User": {
        "properties": {
          "postTown": {
            "type": "string",
            "title": "Posttown"
          }
        },
```

Any help would be great!

**Comment by kattakaha** [comment]
@MCR2019 Hi!　

I simplified the problem and implemented it based on the expectation that when I see:

```python
return {"postTown": "test value"}
```

Here is my code. hello_world/app.py

```python
from aws_lambda_powertools.event_handler import APIGatewayRestResolver
from aws_lambda_powertools.utilities.data_classes import (
    APIGatewayProxyEvent,
    event_source,
)
from aws_lambda_powertools.utilities.typing import LambdaContext
from pydantic import BaseModel
from pydantic.alias_generators import to_camel

app = APIGatewayRestResolver(enable_validation=True)
app.enable_swagger(path="/swagger")


class User(BaseModel):
    class Config:
        alias_generator = to_camel
        populate_by_name = True

    post_town: str


# return : {"postTown": "Tokyo"}, status:200 when you hit the endpoint
@app.get("/user")  # mod endpoint to /user
def get() -> User:
    return User(**{"post_town": "Tokyo"})


@event_source(data_class=APIGatewayProxyEvent)
def lambda_handler(event: APIGatewayProxyEvent, context: LambdaContext):
    return app.resolve(event.raw_event, context)
```

template.yml

```yaml
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  discussion#4507

  Powertools example

Globals: # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-template-anatomy-globals.html
  Function:
    Timeout: 5
    MemorySize: 128
    Runtime: python3.11

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
    Properties:
      Handler: app.lambda_handler
      CodeUri: hello_world
      Description: Hello World function
      Architectures:
        - x86_64
      Tracing: Active
      Events:
        HelloPath:
          Type: Api # More info about API Event Source: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-api.html
          Properties:
            Path: /{proxy+} # FIXED PROXY ENDPOINT
            Method: any # ANY HTTP METHOD 
        # Powertools env vars: https://awslabs.github.io/aws-lambda-powertools-python/#environment-variables
      Environment:
        Variables:
          POWERTOOLS_SERVICE_NAME: PowertoolsHelloWorld
          POWERTOOLS_METRICS_NAMESPACE: Powertools
          LOG_LEVEL: INFO
      Tags:
        LambdaPowertools: python

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod environment for Hello World Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello"

  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
```

## Usage

```bash
sam build
sam local start-api
# Please access http://localhost:3000/swagger using a browser.
```

This is endpoint generated swagger doc.
![image](https://github.com/aws-powertools/powertools-lambda-python/assets/58053010/a58bb009-3eea-4db8-92e7-d6a052e477f6)

Does this answer the question?
